#####  环境：阿里云 ubuntu  python27 tensorflowf1.4.0

## 4.1深度学习与深层神经网络

## 4.2 损失函数的定义
### 4.2.1 经典损失函数

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.4.0'

#### tf.clip_by_value可以把张量中数值限制在某个范围内

In [25]:
v= tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [26]:
sess = tf.Session()
with sess.as_default():
    print(tf.clip_by_value(v,2.5,4.5).eval())
    print("-----------------------------------")
    print (tf.log(v).eval())
    

[[2.5 2.5 3. ]
 [4.  4.5 4.5]]
-----------------------------------
[[0.        0.6931472 1.0986123]
 [1.3862944 1.609438  1.7917595]]


In [28]:
v1= tf.constant([[1.0,2.0],[3.0,4.0]])
v2 = tf.constant([[5.0,6.0],[7.0,8.0]])
sess = tf.Session()
with sess.as_default():
    print ((v1*v2).eval())#按元素相乘
    print(tf.matmul(v1,v2).eval())#矩阵相乘

[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]


### 4.2.2 自定义损失函数

In [29]:
import tensorflow as tf

from numpy.random import RandomState

batch_size = 8

x = tf.placeholder(tf.float32,shape=(None,2),name="x-input")
y_ = tf.placeholder(tf.float32,shape=(None,1),name="y-input")

w1 = tf.Variable(tf.random_normal((2,1),stddev=1,seed=1))
y = tf.matmul(x,w1)

#定义回归预测多了和预测少了的损失函数
loss_less = 10
loss_more = 1
loss = tf.reduce_sum( tf.where(tf.greater(y,y_),(y-y_)*loss_more,(y_-y)*loss_less ))

learning_rate = 0.001
train_step = tf.train.AdamOptimizer(learning_rate).minimize(loss)

#通过随机数生成数据集
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size,2)
#设置回归正确的数值为两个输入的和加上一个随机量。
Y= [[x1+x2+rdm.rand()/10-0.05] for (x1,x2) in X]

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    #初始化变量
    sess.run(init_op)
    
    print sess.run(w1)
    
    STEPS = 5000
    for i in range(STEPS):
        #每次选取batch个样本进行训练
        start = (i*batch_size)%dataset_size
        end = min(start+batch_size,dataset_size)
        
        #通过选取的样本外训练神经网络并更新参数
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
        print (sess.run(w1))


[[-0.8113182]
 [ 1.4845988]]
[[-0.81031823]
 [ 1.4855988 ]]
[[-0.8093366]
 [ 1.4865911]]
[[-0.8083831]
 [ 1.4875891]]
[[-0.8074217]
 [ 1.488542 ]]
[[-0.80644417]
 [ 1.4894979 ]]
[[-0.8054569]
 [ 1.490472 ]]
[[-0.8044624]
 [ 1.4914528]]
[[-0.8034634]
 [ 1.4924384]]
[[-0.80245554]
 [ 1.4934249 ]]
[[-0.80146426]
 [ 1.4944159 ]]
[[-0.80048096]
 [ 1.4954216 ]]
[[-0.79950386]
 [ 1.4964081 ]]
[[-0.79850495]
 [ 1.4974177 ]]
[[-0.7975289]
 [ 1.4984025]]
[[-0.7965442]
 [ 1.4994123]]
[[-0.79556257]
 [ 1.5004357 ]]
[[-0.7946243]
 [ 1.5014318]]
[[-0.7936975]
 [ 1.5024269]]
[[-0.79274493]
 [ 1.5034243 ]]
[[-0.79180086]
 [ 1.504382  ]]
[[-0.7908325]
 [ 1.5053244]]
[[-0.78985554]
 [ 1.5062915 ]]
[[-0.78887033]
 [ 1.5072582 ]]
[[-0.7878793]
 [ 1.5082244]]
[[-0.78687394]
 [ 1.5091867 ]]
[[-0.78588563]
 [ 1.5101508 ]]
[[-0.78490686]
 [ 1.5111339 ]]
[[-0.7839362]
 [ 1.5120951]]
[[-0.78293514]
 [ 1.5130919 ]]
[[-0.7819587]
 [ 1.5140618]]
[[-0.78097296]
 [ 1.5150667 ]]
[[-0.7799913]
 [ 1.5160902]]
[[-0.7790

 [ 1.8716469]]
[[-0.38931996]
 [ 1.8723936 ]]
[[-0.38842234]
 [ 1.8731499 ]]
[[-0.38752386]
 [ 1.8739071 ]]
[[-0.38661164]
 [ 1.8746777 ]]
[[-0.38567862]
 [ 1.8754803 ]]
[[-0.38473576]
 [ 1.876253  ]]
[[-0.38382706]
 [ 1.8769764 ]]
[[-0.38293654]
 [ 1.8777118 ]]
[[-0.38206932]
 [ 1.8783865 ]]
[[-0.38113964]
 [ 1.8791665 ]]
[[-0.3802423]
 [ 1.8799077]]
[[-0.37936184]
 [ 1.8806475 ]]
[[-0.3784931]
 [ 1.8813934]]
[[-0.3776843]
 [ 1.8821024]]
[[-0.37688905]
 [ 1.8828291 ]]
[[-0.3760501]
 [ 1.8835742]]
[[-0.37521103]
 [ 1.8843031 ]]
[[-0.37432194]
 [ 1.8850439 ]]
[[-0.3734309]
 [ 1.8857876]]
[[-0.37252507]
 [ 1.8865467 ]]
[[-0.37159744]
 [ 1.8873397 ]]
[[-0.37065914]
 [ 1.8881042 ]]
[[-0.3697544]
 [ 1.8888202]]
[[-0.36886725]
 [ 1.8895496 ]]
[[-0.3680029]
 [ 1.890219 ]]
[[-0.36709467]
 [ 1.8909588 ]]
[[-0.3662221]
 [ 1.891651 ]]
[[-0.36536372]
 [ 1.8923473 ]]
[[-0.3645146]
 [ 1.8930547]]
[[-0.363737]
 [ 1.893702]]
[[-0.36297414]
 [ 1.8943663 ]]
[[-0.36216384]
 [ 1.8950559 ]]
[[-0.36135027]


 [ 2.1098695 ]]
[[-0.0441488]
 [ 2.1101708]]
[[-0.04355419]
 [ 2.1104562 ]]
[[-0.04301923]
 [ 2.110698  ]]
[[-0.04254403]
 [ 2.1108959 ]]
[[-0.04199991]
 [ 2.1111503 ]]
[[-0.04144364]
 [ 2.111405  ]]
[[-0.04081636]
 [ 2.1117074 ]]
[[-0.04016424]
 [ 2.1120505 ]]
[[-0.03948345]
 [ 2.112425  ]]
[[-0.03878971]
 [ 2.1128151 ]]
[[-0.03804648]
 [ 2.1132321 ]]
[[-0.03730879]
 [ 2.1136434 ]]
[[-0.03660493]
 [ 2.114043  ]]
[[-0.03589615]
 [ 2.114419  ]]
[[-0.03518315]
 [ 2.1148245 ]]
[[-0.034513 ]
 [ 2.1151752]]
[[-0.03389299]
 [ 2.1154797 ]]
[[-0.03329501]
 [ 2.115768  ]]
[[-0.032757 ]
 [ 2.1160123]]
[[-0.03227909]
 [ 2.1162121 ]]
[[-0.03173188]
 [ 2.116469  ]]
[[-0.03117247]
 [ 2.1167262 ]]
[[-0.03054164]
 [ 2.1170318 ]]
[[-0.02988583]
 [ 2.1173785 ]]
[[-0.02920121]
 [ 2.1177568 ]]
[[-0.02850355]
 [ 2.118151  ]]
[[-0.02775614]
 [ 2.1185722 ]]
[[-0.02701432]
 [ 2.1189878 ]]
[[-0.0263065]
 [ 2.1193917]]
[[-0.02559376]
 [ 2.1197715 ]]
[[-0.02487678]
 [ 2.1201813 ]]
[[-0.02420288]
 [ 2.1205356 ]]


 [2.2028563]]
[[0.19443443]
 [2.2029226 ]]
[[0.1949469]
 [2.2030423]]
[[0.19544335]
 [2.2031577 ]]
[[0.19596069]
 [2.2033045 ]]
[[0.19648063]
 [2.2034578 ]]
[[0.19705063]
 [2.2036307 ]]
[[0.19760188]
 [2.2037752 ]]
[[0.19811812]
 [2.2039046 ]]
[[0.198671 ]
 [2.2040417]]
[[0.19919014]
 [2.2041714 ]]
[[0.19969052]
 [2.2042692 ]]
[[0.2001604]
 [2.2043424]]
[[0.20059542]
 [2.2043848 ]]
[[0.20098001]
 [2.204397  ]]
[[0.20131849]
 [2.2043817 ]]
[[0.20171732]
 [2.2044168 ]]
[[0.20215471]
 [2.2044816 ]]
[[0.20266892]
 [2.2046006 ]]
[[0.20316719]
 [2.2047155 ]]
[[0.20364691]
 [2.204823  ]]
[[0.20413336]
 [2.2049413 ]]
[[0.20467393]
 [2.205083  ]]
[[0.20519894]
 [2.2051992 ]]
[[0.20569168]
 [2.2053032 ]]
[[0.20622402]
 [2.2054176 ]]
[[0.20672482]
 [2.2055268 ]]
[[0.2072089]
 [2.2056062]]
[[0.20766424]
 [2.2056625 ]]
[[0.20808624]
 [2.2056897 ]]
[[0.20845905]
 [2.2056875 ]]
[[0.20878688]
 [2.2056594 ]]
[[0.20917675]
 [2.205683  ]]
[[0.20960663]
 [2.205738  ]]
[[0.21011493]
 [2.205849  ]]
[[0.2106

 [2.198693  ]]
[[0.38346535]
 [2.198574  ]]
[[0.38380384]
 [2.1984365 ]]
[[0.38409996]
 [2.1982787 ]]
[[0.38435256]
 [2.1980991 ]]
[[0.38464284]
 [2.1979535 ]]
[[0.38496196]
 [2.197829  ]]
[[0.38534486]
 [2.1977437 ]]
[[0.3857105]
 [2.1976557]]
[[0.3860681]
 [2.1975698]]
[[0.38641015]
 [2.1974723 ]]
[[0.38684222]
 [2.1974301 ]]
[[0.3872775]
 [2.1973774]]
[[0.38766262]
 [2.1972952 ]]
[[0.3881166]
 [2.1972482]]
[[0.38850045]
 [2.1971645 ]]
[[0.38887683]
 [2.197053  ]]
[[0.3892392]
 [2.196933 ]]
[[0.38957992]
 [2.1967943 ]]
[[0.389878]
 [2.196635]]
[[0.39013228]
 [2.1964538 ]]
[[0.39042446]
 [2.1963067 ]]
[[0.3907457]
 [2.196181 ]]
[[0.39113113]
 [2.196095  ]]
[[0.39145884]
 [2.195975  ]]
[[0.39178246]
 [2.1958604 ]]
[[0.39209405]
 [2.1957366 ]]
[[0.39249954]
 [2.1956713 ]]
[[0.3929112]
 [2.1955976]]
[[0.39327496]
 [2.1954963 ]]
[[0.39371046]
 [2.1954322 ]]
[[0.3940775]
 [2.1953328]]
[[0.39443892]
 [2.1952066 ]]
[[0.39478797]
 [2.1950734 ]]
[[0.3951168]
 [2.1949224]]
[[0.39540413]
 [2.194

 [2.1191168 ]]
[[0.53025836]
 [2.1188886 ]]
[[0.53057843]
 [2.1186647 ]]
[[0.5308584]
 [2.1184192]]
[[0.5311965]
 [2.1182024]]
[[0.53147095]
 [2.117955  ]]
[[0.531755 ]
 [2.1176867]]
[[0.53203887]
 [2.1174204 ]]
[[0.53231186]
 [2.117142  ]]
[[0.5325472]
 [2.116848 ]]
[[0.5327421]
 [2.1165357]]
[[0.532949 ]
 [2.1162393]]
[[0.5332051]
 [2.1159809]]
[[0.5335257]
 [2.1157637]]
[[0.5337911]
 [2.1155145]]
[[0.5340072]
 [2.1152413]]
[[0.53422594]
 [2.1149697 ]]
[[0.53452116]
 [2.1147392 ]]
[[0.53484285]
 [2.1145132 ]]
[[0.53512424]
 [2.1142654 ]]
[[0.53546417]
 [2.1140466 ]]
[[0.5357401]
 [2.113797 ]]
[[0.53602564]
 [2.1135263 ]]
[[0.53631115]
 [2.1132576 ]]
[[0.5365857]
 [2.1129768]]
[[0.5368223]
 [2.1126802]]
[[0.5370183]
 [2.1123652]]
[[0.5372264]
 [2.1120663]]
[[0.53748405]
 [2.1118057 ]]
[[0.53780663]
 [2.1115866 ]]
[[0.5380737]
 [2.1113355]]
[[0.5382911]
 [2.1110601]]
[[0.5385112]
 [2.1107864]]
[[0.5388083]
 [2.1105542]]
[[0.53913206]
 [2.1103263 ]]
[[0.53941524]
 [2.1100764 ]]
[[0.5397

 [1.9680651]]
[[0.6349705]
 [1.9676963]]
[[0.63521  ]
 [1.9673353]]
[[0.6353976]
 [1.9669449]]
[[0.63553905]
 [1.9665337 ]]
[[0.63569546]
 [1.966132  ]]
[[0.6359543]
 [1.9657876]]
[[0.63621044]
 [1.9654269 ]]
[[0.6364311]
 [1.965048 ]]
[[0.63673383]
 [1.964712  ]]
[[0.6369701]
 [1.9643452]]
[[0.6372275]
 [1.963959 ]]
[[0.63743114]
 [1.9635414 ]]
[[0.63763547]
 [1.9631177 ]]
[[0.6378068]
 [1.962683 ]]
[[0.63794047]
 [1.962233  ]]
[[0.63809884]
 [1.961809  ]]
[[0.6383258]
 [1.9614378]]
[[0.6385668]
 [1.9610745]]
[[0.6387556]
 [1.9606814]]
[[0.63889796]
 [1.9602674 ]]
[[0.6390554]
 [1.9598631]]
[[0.63931584]
 [1.9595164 ]]
[[0.6395736]
 [1.9591532]]
[[0.6397956]
 [1.9587717]]
[[0.6401002]
 [1.9584336]]
[[0.64033794]
 [1.9580644 ]]
[[0.6405969]
 [1.9576756]]
[[0.6408019]
 [1.9572551]]
[[0.64100754]
 [1.9568287 ]]
[[0.6411799]
 [1.9563911]]
[[0.64131445]
 [1.9559381 ]]
[[0.64147377]
 [1.9555115 ]]
[[0.6417022]
 [1.9551377]]
[[0.64194465]
 [1.9547719 ]]
[[0.64213467]
 [1.9543762 ]]
[[0.64227

 [1.7694759]]
[[0.73452646]
 [1.7689551 ]]
[[0.73472476]
 [1.7684298 ]]
[[0.7348883]
 [1.7678934]]
[[0.7350113]
 [1.7673411]]
[[0.73516685]
 [1.7668216 ]]
[[0.7354067]
 [1.7663662]]
[[0.7356659]
 [1.7659216]]
[[0.735866 ]
 [1.7654432]]
[[0.7360134]
 [1.7649412]]
[[0.7361807]
 [1.7644517]]
[[0.7363979]
 [1.7639933]]
[[0.73662096]
 [1.7635199 ]]
[[0.7368099]
 [1.7630291]]
[[0.73710376]
 [1.7625935 ]]
[[0.7373252]
 [1.7621245]]
[[0.7375776]
 [1.7616354]]
[[0.7377715]
 [1.7611117]]
[[0.737971 ]
 [1.7605834]]
[[0.7381355]
 [1.7600441]]
[[0.7382592]
 [1.7594887]]
[[0.7384157]
 [1.7589662]]
[[0.738657 ]
 [1.7585082]]
[[0.73891777]
 [1.758061  ]]
[[0.7391191]
 [1.7575799]]
[[0.7392674]
 [1.7570751]]
[[0.73943573]
 [1.7565829 ]]
[[0.73965424]
 [1.7561218 ]]
[[0.7398786]
 [1.7556458]]
[[0.7400687]
 [1.7551522]]
[[0.74036425]
 [1.7547141 ]]
[[0.740587 ]
 [1.7542425]]
[[0.7408409]
 [1.7537507]]
[[0.741036]
 [1.753224]]
[[0.7412367]
 [1.7526927]]
[[0.7414022]
 [1.7521503]]
[[0.74152666]
 [1.7515918

 [1.5241243 ]]
[[0.8245326]
 [1.523552 ]]
[[0.82469386]
 [1.5229669 ]]
[[0.82482505]
 [1.5223656 ]]
[[0.82508844]
 [1.5218314 ]]
[[0.82527494]
 [1.5212618 ]]
[[0.82552403]
 [1.5206959 ]]
[[0.8257091]
 [1.5200902]]
[[0.82590497]
 [1.5194794 ]]
[[0.8260636]
 [1.518856 ]]
[[0.8261777]
 [1.5182142]]
[[0.82633346]
 [1.5176105 ]]
[[0.82652915]
 [1.5170534 ]]
[[0.82675636]
 [1.5165116 ]]
[[0.82692164]
 [1.5159332 ]]
[[0.82705057]
 [1.5153558 ]]
[[0.8272075]
 [1.5147926]]
[[0.82736677]
 [1.5142387 ]]
[[0.8275426]
 [1.5136698]]
[[0.8276869]
 [1.5130827]]
[[0.82796293]
 [1.5125614 ]]
[[0.8281605]
 [1.5120031]]
[[0.82842 ]
 [1.511447]]
[[0.82861423]
 [1.5108496 ]]
[[0.8288185]
 [1.5102459]]
[[0.82898456]
 [1.5096287 ]]
[[0.82910526]
 [1.508992  ]]
[[0.8292672]
 [1.5083928]]
[[0.8294688]
 [1.5078396]]
[[0.82970166]
 [1.5073011 ]]
[[0.8298718]
 [1.5067253]]
[[0.83000493]
 [1.5061501 ]]
[[0.8301659]
 [1.5055885]]
[[0.83032894]
 [1.5050359 ]]
[[0.83050835]
 [1.5044678 ]]
[[0.83065575]
 [1.5038811 ]]


 [1.244254  ]]
[[0.9167364]
 [1.2436494]]
[[0.9169338]
 [1.2430027]]
[[0.9170884]
 [1.2423564]]
[[0.91727495]
 [1.2417254 ]]
[[0.91746384]
 [1.2411045 ]]
[[0.91767156]
 [1.2404661 ]]
[[0.91784227]
 [1.2398067 ]]
[[0.91816545]
 [1.2392212 ]]
[[0.9183973]
 [1.2385935]]
[[0.9187007]
 [1.237968 ]]
[[0.91892815]
 [1.2372956 ]]
[[0.91916704]
 [1.2366158 ]]
[[0.9193614]
 [1.2359204]]
[[0.919503 ]
 [1.2352029]]
[[0.9196922]
 [1.2345276]]
[[0.91992724]
 [1.233904  ]]
[[0.92019844]
 [1.233297  ]]
[[0.92039675]
 [1.2326478 ]]
[[0.9205521]
 [1.231999 ]]
[[0.9207396]
 [1.2313657]]
[[0.9209294]
 [1.2307423]]
[[0.9211381]
 [1.2301015]]
[[0.92130965]
 [1.2294395 ]]
[[0.9216344]
 [1.2288518]]
[[0.9218674]
 [1.2282215]]
[[0.9221722]
 [1.2275935]]
[[0.9224007]
 [1.2269186]]
[[0.92264074]
 [1.2262361 ]]
[[0.92283607]
 [1.2255381 ]]
[[0.9229783]
 [1.2248179]]
[[0.9231685]
 [1.2241399]]
[[0.92340463]
 [1.223514  ]]
[[0.92367715]
 [1.2229047 ]]
[[0.9238764]
 [1.2222528]]
[[0.9240325]
 [1.2216016]]
[[0.924220

 [1.0448254]]
[[1.0189563]
 [1.0448296]]
[[1.0189824]
 [1.0447425]]
[[1.0190278]
 [1.0446962]]
[[1.0190085]
 [1.0445534]]
[[1.0190266]
 [1.0446184]]
[[1.0191101]
 [1.0446273]]
[[1.0191722]
 [1.0447348]]
[[1.019202 ]
 [1.0447618]]
[[1.0191805]
 [1.0447031]]
[[1.0191131]
 [1.0446168]]
[[1.0190147]
 [1.0444494]]
[[1.0189908]
 [1.044296 ]]
[[1.0189632]
 [1.0441016]]
[[1.0189601]
 [1.0440018]]
[[1.0189743]
 [1.044145 ]]
[[1.0189353]
 [1.0441546]]
[[1.0189389]
 [1.0440822]]
[[1.0189186]
 [1.0439262]]
[[1.0189224]
 [1.0438179]]
[[1.0188652]
 [1.0436193]]
[[1.0188495]
 [1.0436339]]
[[1.0189029]
 [1.0435977]]
[[1.0189378]
 [1.0436645]]
[[1.018943 ]
 [1.0436547]]
[[1.0188991]
 [1.043563 ]]
[[1.0188111]
 [1.043447 ]]
[[1.018694 ]
 [1.0432531]]
[[1.0187411]
 [1.0432101]]
[[1.0187774]
 [1.0431153]]
[[1.018832]
 [1.043105]]
[[1.0188981]
 [1.0433282]]
[[1.0189056]
 [1.04341  ]]
[[1.0189513]
 [1.0434026]]
[[1.0189688]
 [1.0433053]]
[[1.0190067]
 [1.0432497]]
[[1.0189799]
 [1.0430988]]
[[1.0189917]
 [1

## 4.3 神经网络的优化算法

#### 正则化样例代码

In [30]:
weights = tf.constant([[1.0,-2.0],[-3.0,4.0]])
with tf.Session() as sess:
    print(sess.run( tf.contrib.layers.l1_regularizer(.5)(weights) ))
    print(sess.run( tf.contrib.layers.l2_regularizer(.5)(weights) ))

5.0
7.5


#### 计算一个5层神经网络带L2正则化的损失函数的计算方法

In [ ]:
#  非完整可执行代码片段
#   ??这个代码要干啥呀！！
import tensorflow as tf 

# 获取一层神经网络边的权重，并将这个权重的L2正则化损失加入到名称为‘losses’的集合中
def get_weight(shape,lambdaa):#lambdaa!!!
    #生成一个变量
    var = tf.Variable(tf.random_normal(shape),dtype=tf.float32)
    # 第一个参数是集合的名字
    tf.add_to_collection('losses',tf.contrib.layers.l2_regularizer(lambdaa)(var))
    return var

x = tf.placeholder(tf.float32,shape=(None,2))
y_ = tf.placeholder(tf.float32,shape=(None,1))

batch_size = 8

layer_dimension = [2,10,10,10,1]
n_layers = len(layer_dimension)

#这个变量维护前向传播最深的节点，开始的时候就是输入层
cur_layer = x
#当前层节点的个数
in_dimension = layer_dimension[0]

# 通过一个循环生成5层全连接神经网络结构
for i in range(1,n_layers):
    # layer_dimension[i] 为下一层节点的个数
    out_dimension = layer_dimension[i]
    # 生成当前层中的变量，并将这个变量的L2正则化损失加入计算图上的集合
    weight = get_weight([in_dimension,out_dimension],0.001)
    bias = tf.Variable(tf.constant(0.1,shape=[out_dimension]))
    cur_layers = tf.nn.relu(tf.matmul(cur_layers,weight) + bias)
    # 进入下一层之前将下一层的节点个数更新为当前层节点的个数
    in_dimension = layer_dimension[i]
    
mse_loss = tf.reduce_mean(tf.square(y_-cur_layer))

tf.add_to_collection('losses',mse_loss)

loss = tf.add_n(tf.get_collection('losses'))
    

### 4.4.3 滑动平均模型

In [36]:
import tensorflow as tf

v1 = tf.Variable(0,dtype=tf.float32)
step = tf.Variable(0,trainable=False)

ema = tf.train.ExponentialMovingAverage(0.99,step)
maintain_averages_op = ema.apply([v1])
with tf.Session() as sess:
    #初始化所有变量
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
    # 初始化后变量的值以及滑动平均后的值
    print sess.run([v1,ema.average(v1)])
    
    #更新v1的值到5
    sess.run(tf.assign(v1,5))
    sess.run(maintain_averages_op)
    print (sess.run([v1,ema.average(v1)]))
    
    sess.run(maintain_averages_op)
    print (sess.run([v1,ema.average(v1)]))

[0.0, 0.0]
[5.0, 4.5]
[5.0, 4.95]
